name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=SonarTest
            -Dsonar.sources=src
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=sqp_8a71677e5ebea449ec83fbec408fff4452f29d9b